org: jerinpetergeorge
app: generic-django-example
service: generic-django-example

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  pythonRequirements:
    fileName: requirements/serverless.txt
    usePipenv: false
    dockerizePip: non-linux
  wsgi:
    app: config.wsgi.application
    packRequirements: false
