# Generated by Django 3.2.7 on 2021-09-26 20:18

from django.db import migrations, models
import utils.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyFieldModel',
            fields=[
                ('id', utils.db.fields.TinyAutoField(primary_key=True, serialize=False)),
                ('any_number', models.IntegerField(default=10)),
            ],
        ),
    ]
