# Generated by Django 3.2.14 on 2022-08-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', related_query_name='choice', to='polls.poll'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
